version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: test_db
    restart: always
    volumes:
      - ${PWD}/data/bulk_data.sh:/docker-entrypoint-initdb.d/init.sh
      - ${PWD}/data:/data
    networks:
      - app_network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app_network

  api:
    image: ml-anomaly-detector
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - INSTALL_DEV_DEPENDENCIES="true"
    ports:
      - 8000:8000
    env_file:
      - .env.example
    depends_on:
     - redis
     - mongo
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
